In [7]:
# step-1 :we have to import the dataset to the colab notebook
import pandas as pd #pd is a nick name for pandas
df=pd.read_csv('Data.csv')

In [8]:
type(df)

pandas.core.frame.DataFrame

In [9]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [10]:
#step 2:grouping the input columns and output columns
x=df.iloc[:,:3]

In [11]:
x

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [12]:
y=df.iloc[:,3]

In [13]:
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [14]:
x=x.values

In [15]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [16]:
y =y.values

In [17]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [18]:
 #step 3: handling the missing value are data
 #scenario-1 missing value in numerical coloumn
 #calcuate the mean are average and replace the empty values
 #scenario-2 missing values in non numerical values
 #scenario-3 having missing value in huge dataset
 import numpy as np
 from sklearn.impute import SimpleImputer
 imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
 imputer.fit(x[:,1:3])
 x[:,1:3]=imputer.transform(x[:,1:3])




In [19]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [20]:
#step-4 handling catogorial data
#which convert the text data into numeric data
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer#column transformer which is used to apply change of catogorical data to numerical data

#alexa-0,0,1

ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')#encoder is method which convert text to binary
np.remainder='passthrough'
x=ct.fit_transform(x)

In [21]:
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [22]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [23]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [24]:
#step 5 slip the data into training and testing data
from sklearn.model_selection import train_test_split #tain is a class which was imported sklear from sk.model selection. it was used to split the data intotesting and training
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2)


In [25]:
x_train

array([[0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0]], dtype=object)

In [26]:
x_test

array([[1.0, 0.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0]], dtype=object)

In [27]:
y_train

array([0, 1, 1, 0, 1, 0, 0, 0])

In [28]:
y_test

array([1, 1])

In [29]:
#step-6: feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:,3:]=sc.fit_transform(x_train[:,3:])
x_test[:,3:]=sc.transform(x_test[:,3:])



In [30]:
x_train

array([[0.0, 0.0, 1.0, 0.09999937526616287, -0.9842949179873288],
       [1.0, 0.0, 0.0, -0.16122348257197638, 0.40894035255830086],
       [0.0, 0.0, 1.0, -1.630602057911509, -1.3558243234661633],
       [0.0, 1.0, 0.0, -1.1897884853096492, -0.7985302152479116],
       [0.0, 1.0, 0.0, 0.2795900900298834, 0.1096527759225733],
       [0.0, 0.0, 1.0, -0.014285625038023117, -0.14835375565995101],
       [0.0, 1.0, 0.0, 1.7489686653694159, 1.8950579744736393],
       [1.0, 0.0, 0.0, 0.8673415201656964, 0.8733521094068442]],
      dtype=object)

In [31]:
x_test

array([[1.0, 0.0, 0.0, -0.4550991976398829, -0.42700080976907695],
       [1.0, 0.0, 0.0, 1.4550929503015095, 1.5235285689948046]],
      dtype=object)

In [32]:
#machine learning
#supervise learning -when have labled the data ,and model tasks are classified or predictor
#1 .linear regration 2.logistic algerthem
#unsupervise learning -unlabled data,model performes or remembers the patterns, we can perform predictions also.
#reinforcement learning -trail and error method ,model learns fromfailures


In [33]:
#logistic regresion algorithm
#when model performing classifiction task we have apply to logistic regration algerthem
#when model performs prediction task we have apply to linear regration algerthem
#step7:applying the algorithm to the training data
from sklearn.linear_model import LogisticRegression
Classifier=LogisticRegression()
Classifier.fit(x_train,y_train)

LogisticRegression()

In [34]:
y_pred=Classifier.predict(x_test)

In [36]:
y_pred

array([1, 0])